package debug

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// ConnectionInfo carries the minimum connection details needed to reconstruct
// an equivalent `mcp-tui` CLI invocation for a recorded session. It is a plain
// value struct so the debug package does not need to import the config package
// (which would create an import cycle) — callers translate their own
// ConnectionConfig into this shape.
type ConnectionInfo struct {
	Transport string // "stdio", "sse", "http", "streamable-http"
	Command   string // STDIO server command
	Args      []string
	URL       string // HTTP/SSE server URL
}

// BuildReplayScript turns a recorded event stream into a runnable shell script
// of equivalent `mcp-tui` CLI commands. Only replayable client→server requests
// (tools/call, resources/read, prompts/get) are translated — every other event
// type is skipped. The script is directly usable for CLI automation: it targets
// the same server the recording was made against.
func BuildReplayScript(events []*Event, conn ConnectionInfo) string {
	base := baseInvocation(conn)

	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by mcp-tui session recording.\n")
	b.WriteString("# Each line replays one recorded MCP request against the same server.\n")
	b.WriteString("set -euo pipefail\n\n")

	count := 0
	for _, ev := range events {
		if ev == nil || ev.Type != EventRequestSent {
			continue
		}
		line, ok := translateRequest(base, ev.Method, requestParams(ev))
		if !ok {
			continue
		}
		b.WriteString(line)
		b.WriteString("\n")
		count++
	}

	if count == 0 {
		b.WriteString("# (no replayable requests were recorded)\n")
	}

	return b.String()
}

// baseInvocation builds the shared `mcp-tui <connection flags>` prefix.
func baseInvocation(conn ConnectionInfo) string {
	parts := []string{"mcp-tui"}
	switch conn.Transport {
	case "sse", "http", "streamable-http":
		parts = append(parts, "--transport", conn.Transport)
		if conn.URL != "" {
			parts = append(parts, "--url", shellQuote(conn.URL))
		}
	default: // stdio (also the empty/unknown fallback)
		if conn.Command != "" {
			parts = append(parts, "--cmd", shellQuote(conn.Command))
		}
		if len(conn.Args) > 0 {
			parts = append(parts, "--args", shellQuote(strings.Join(conn.Args, ",")))
		}
	}
	return strings.Join(parts, " ")
}

// translateRequest maps a single MCP request to its CLI equivalent. Returns
// ok=false for methods that have no direct CLI subcommand.
func translateRequest(base, method string, params map[string]interface{}) (string, bool) {
	switch method {
	case "tools/call":
		name, _ := params["name"].(string)
		if name == "" {
			return "", false
		}
		cmd := fmt.Sprintf("%s tool call %s", base, shellQuote(name))
		for _, kv := range keyValueArgs(params["arguments"]) {
			cmd += " " + shellQuote(kv)
		}
		return cmd, true

	case "resources/read":
		uri, _ := params["uri"].(string)
		if uri == "" {
			return "", false
		}
		return fmt.Sprintf("%s resource get %s", base, shellQuote(uri)), true

	case "prompts/get":
		name, _ := params["name"].(string)
		if name == "" {
			return "", false
		}
		args := keyValueArgs(params["arguments"])
		if len(args) == 0 {
			// `prompt get` fetches the prompt without arguments.
			return fmt.Sprintf("%s prompt get %s", base, shellQuote(name)), true
		}
		// `prompt execute` accepts per-argument --arg flags.
		cmd := fmt.Sprintf("%s prompt execute %s", base, shellQuote(name))
		for _, kv := range args {
			cmd += " --arg " + shellQuote(kv)
		}
		return cmd, true

	default:
		return "", false
	}
}

// requestParams extracts the JSON-RPC params map from a traced request event.
// The tracing middleware records the whole SDK request object, so the actual
// params may sit under a capitalised "Params" key (Go field name, since the
// SDK request wrapper carries no json tags) or, for hand-built events, at the
// top level. Both shapes are handled, plus a lowercase "params" fallback.
func requestParams(ev *Event) map[string]interface{} {
	raw, ok := ev.Data["params"]
	if !ok {
		return nil
	}
	m, ok := raw.(map[string]interface{})
	if !ok {
		return nil
	}
	if inner, ok := m["Params"].(map[string]interface{}); ok {
		return inner
	}
	if inner, ok := m["params"].(map[string]interface{}); ok {
		return inner
	}
	return m
}

// keyValueArgs renders a tool/prompt arguments object into stable, sorted
// "key=value" strings. String values are used verbatim; every other value is
// JSON-encoded so the CLI's type-conversion layer can round-trip it.
func keyValueArgs(v interface{}) []string {
	m, ok := v.(map[string]interface{})
	if !ok || len(m) == 0 {
		return nil
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	out := make([]string, 0, len(keys))
	for _, k := range keys {
		out = append(out, k+"="+scalarString(m[k]))
	}
	return out
}

// scalarString renders a JSON value for use on the right side of key=value.
func scalarString(v interface{}) string {
	if s, ok := v.(string); ok {
		return s
	}
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("%v", v)
	}
	return string(b)
}

// shellQuote wraps a token in single quotes so spaces and shell metacharacters
// survive as a single argument. Embedded single quotes are escaped with the
// standard '\'' idiom. Simple tokens (safe characters only) are returned as-is
// to keep the common case readable.
func shellQuote(s string) string {
	if s != "" && !strings.ContainsAny(s, " \t\n\"'\\$`&|;<>()*?![]{}#~") {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
