#!/bin/bash

echo "Manual test for keyboard issues in mcp-tui"
echo "=========================================="
echo ""
echo "1. Testing Ctrl+C on inspection screen:"
echo "   - Run: ./mcp-tui"
echo "   - Connect to a server"
echo "   - When on the inspection screen (showing tools/resources/prompts)"
echo "   - Press Ctrl+C"
echo "   - EXPECTED: Should quit the program"
echo "   - ACTUAL: Does not quit (BUG)"
echo ""
echo "2. Testing 'q' key on inspection screen:"
echo "   - Same setup as above"
echo "   - Press 'q'"
echo "   - EXPECTED: Should quit the program"
echo "   - ACTUAL: Quits correctly (WORKS)"
echo ""
echo "3. Testing Ctrl+L to toggle debug log:"
echo "   - Same setup as above"
echo "   - Press Ctrl+L"
echo "   - EXPECTED: Should switch to debug log view"
echo "   - ACTUAL: Does not switch (POSSIBLE BUG)"
echo ""
echo "To run the test, build and execute:"
echo "go build -o mcp-tui . && ./mcp-tui"